### ISSUE TITLE
An error occurred when using “Update Script with Translation”.   -(InProgress)-

### ISSUE THREAD

**Issue by NoclubOIRzXx** [IN2-Moist/2Take1-Moist-Script#12]
[2023-05-09 01:18:40] [Lua Exception] [Failed to resume coroutine] ...arDevs\2Take1Menu\scripts\MoistFiles\Moist_Translate.lua:146: attempt to index a number value (field 'Weather')
stack traceback:
	...arDevs\2Take1Menu\scripts\MoistFiles\Moist_Translate.lua:146: in field 'localmenu'
	?: in function <?:561>
	
![image](https://user-images.githubusercontent.com/40497676/236889023-d5d9f0b3-0c15-478a-8013-f4de41a72f86.png)
![image](https://user-images.githubusercontent.com/40497676/236889081-2fb17264-2ac6-477f-8864-6f79b8c236d3.png)

**Comment by NoclubOIRzXx** [comment]
Causing the translation below line 146 to be ineffective.

**Comment by IN2-Moist** [comment]
> [2023-05-09 01:18:40] [Lua Exception] [Failed to resume coroutine] ...arDevs\2Take1Menu\scripts\MoistFiles\Moist_Translate.lua:146: attempt to index a number value (field 'Weather') stack traceback: ...arDevs\2Take1Menu\scripts\MoistFiles\Moist_Translate.lua:146: in field 'localmenu' ?: in function <?:561>
> 
> ![image](https://user-images.githubusercontent.com/40497676/236889023-d5d9f0b3-0c15-478a-8013-f4de41a72f86.png) ![image](https://user-images.githubusercontent.com/40497676/236889081-2fb17264-2ac6-477f-8864-6f79b8c236d3.png)

Could you ensure you completely unload the scripts loading them from a fresh game start, Due to the way some of the required files are loaded 2t1 caches alot of this data and could just need to clear, the unload method is literally a Delete everything  & load the updated files. Only way possible to do it without the user having to go  and turn it back on.
I did not get any issues when i tested it last night, but looking at it i found some functions there that would never get translated due to creating them without a set variable, the weather functions are going to be consolodated into a single string value modify feature and all given variables which i will add to the translation script. Will Push an updated version in the next few hours.

**Comment by IN2-Moist** [comment]
@NoclubOIRzXx Issue has Been Resolved

https://github.com/IN2-Moist/2Take1-Moist-Script/releases/tag/3.0.2.0.BugFix.2

Please open another issue if you stil get any issues, it had no errors when i tried it not long ago.  Was a small typo Camel Case Variable was missing a Capital.
