### ISSUE TITLE
Faild to resume coroutine

### ISSUE THREAD

**Issue by realrEDGUY** [IN2-Moist/2Take1-Moist-Script#4]
Error on load

MoistScript.lua:3019: atte
[Picture](https://xn--pcktb1c2c9f.140er.club/g27FOVOwpj.png)

**Comment by IN2-Moist** [comment]
@realrEDGUY 
this is the point where the script is already broken from whatever you last did in the script or one of its background functions
really need the error data from the log the notifys dont give the data to be able to see what caused it!
here's an example:

`[2021-05-23 07:29:42] [Error] [Failed to resume coroutine] ...a\Roaming\PopstarDevs\2Take1Menu\scripts\\MoistScript.lua:13821: bad argument #1 to 'ScriptTR' (number expected, got string)
stack traceback:
    [C]: in upvalue 'ScriptTR'
    ...a\Roaming\PopstarDevs\2Take1Menu\scripts\\MoistScript.lua:13821: in function <...a\Roaming\PopstarDevs\2Take1Menu\scripts\\MoistScript.lua:13805>`

there will be some problems fixed in the next release when im done fixing what i broken in the last week or so.

Please give details what you were doing at the time the error occurs and search the 2take1menu.log file for the last error and grab all the stack traceback error data too and open a new issue.
1 error can start at line 138 but be caused from a line like 13896 where part of the function there used another at line 138 so very important to have the data or at least what was happening or what you were doing at that point in time

I will close this issue due to not having the info to be able to investigate further !
