### ISSUE TITLE
Moist Script Loader - sorting

### ISSUE THREAD

**Issue by mgavdhout** [IN2-Moist/2Take1-Moist-Script#8]
I installed today the LATEST **2Take1Script.lua** but am not able to get the sorting order sorted the way i want/had it.

Whatever I try, its not getting in the order, and I am so used to that order:
1 - Moist
2 - Kek's
3 - 2Take1Script
4 - Heist Control
5 - Master Unlocker
6 - Meteor

While before the update of 2Take1Script.lua, the sorting order was like above. Now it keeps appearing like below picture.

![image](https://user-images.githubusercontent.com/96773003/170253772-d9484c29-4bc1-46db-826f-5d4435ee5081.png)

**Comment by IN2-Moist** [comment]
are you still using Moist script to load these files?
try resetting saved scripts in the script loader
load them in order you like save
see if its the same.
would have said its due to loading the save file and putting the data in the table to store before execution and it going via order of names but that dont look right as 2take1 script would be first
Moist Script 2.x.x.x is being discontinued as im working on a rewrite currently in beta test
will look at adding these features over soon
